---
output: html_fragment
---

**CovidR** is an [e-Rum2020 **pre-conference event**](https://2020.erum.io/covidr-contest/) featuring a contest of R contributions around the topic of the [COVID-19 pandemic](https://www.who.int/emergencies/diseases/novel-coronavirus-2019).

Contributions can be submitted **until May 22nd**, and the online e-Rum2020 pre-conference event will be held on **May 29th**. Selected contributors will be invited to present their work to the community at the event, where the CovidR contest winner(s) will be announced and will receive their e-prizes. Finally, the best overall contribution will also be invited to present at the main e-Rum2020 conference (June 17th-20th).

### Philosophy

**_The contest in the right context_** &mdash; Due to the relevance of the topic, we would like to clarify some points so that both the participants and their audience correctly engage with the CovidR contest.

The COVID-19 data assets made available by authoritative institutions are immensely useful. However, their incompleteness and differences in collection policies may open up to misunderstanding and miscommunication. Data scientists should force themselves to be responsible data narrators and communicators. 
To what extent can Rstats be a tool for data narrative? Can we use our tools to uncover missing data and data wrong-doing?
A beautiful visualization is not necessarily about beautiful data, but it’s beautiful when it allows people to understand what we know as well as (more often) what we actually do not.

The CovidR contest is mostly about R analytics technicalities and for data geeks, but it’s open to data scientists, analysts, academics and researchers that may use the single simplest R function, but just on the right question, at the right time, tackling the many doubts cast by this so vast paradigmatic change we’re all living.
Being original in the contest means being able to address different aspects of the pandemics. The CovidR contest is looking for such excellence and originality and we will also judge how R analytics can be an efficient and valid technical service to this effort and in such a context.

### How to participate

- Provide us with your contribution by May 22nd using the GitHub repository, following the instructions in the ['Submit'](`r submit_link`) section.
- A GitHub account is needed in order to submit a contribution.

### What you will get

- All contributions will be featured in the [CovidR Gallery](https://milano-r.github.io/erum2020-covidr-contest) website, allowing the community to browse through and vote for your contribution.
- Each participant will get a CovidR badge to include in their repository.
- We will share contributions on our social media.
- Selected contributions will be presented at the e-Rum2020 pre-conference event on May 29th.
- Winner(s) will be awarded with e-prizes.
- The ultimate contest winner will be invited to present at [e-Rum2020](https://2020.erum.io/).

### How to win

An internal jury will pick the winner(s) by evaluating:

- technical quality of the work &ndash; i.e. interesting, innovative and best-practice usage of the R language;
- popularity of the work among the community &ndash; based on thumbs up in the CovidR Gallery.

The winner(s) will be announced during the pre-conference event on May 29th.

### Participation rules

- Any work or analysis must be performed starting from official data (governmental, institutional, national or international), providing complete reference to sources.
- Data used can directly refer to the SARS-CoV-2 outbreak (official number of cases, tests performed, viral genome sequences, ...) or to different metrics that can affect the course of the infection if put in the context of the outbreak (demography, population density, census, geographic distributions, movements, ...).
- Work can refer to a single specific country, a group of countries or the whole globe.
- Work or analyses must wholly or at least for a relevant part rely on R-based analytics. 
- Data and source code must be open sourced and available through an open repository.
- Work can be of any kind, from original data analyses, models, to interactive dashboards or infographics. 

If you have general questions you can always contact us at [covidrcontest@erum.io](mailto:covidrcontest@erum.io), otherwise we recommend using the [Issue / Pull Request submission mechanism](`r submit_link`) as a channel for discussing how you can submit your contribution.
