#!/bin/bash
if [[ README.Rmd -nt README.md ]]; then
  echo "README.md is out of date; please re-knit README.Rmd"
  exit 1
fi
if [[ _fragments/covidr-intro.Rmd -nt README.md ]]; then
  echo "covidr-intro.Rmd was updated; please re-knit README.Rmd"
  exit 1
fi
if [[ contest/contributions/.example.yml -nt README.md ]]; then
  echo ".example.yml was updated; please re-knit README.Rmd"
  exit 1
fi
if [[ CODE_OF_CONDUCT.md -nt README.md ]]; then
  echo "CODE_OF_CONDUCT.md was updated; please re-knit README.Rmd"
  exit 1
fi
