# Contribution's title, author, abstract
title: An Awesome COVID-19 Contribution # title case
author: An Author, Another Author # comma-separated
abstract: |
  Provide a short abstract with a brief description of your contribution and its
  main features (max 800 characters, including spaces). The usage of publicly
  available data should be explictly mentioned.
  The text can be broken across multiple lines, each indented with two spaces.

# Short name to be used in the website Gallery menu (can be the same as title)
menu_entry: Short title
# URL of the public source code repository
repository: https://github.com/user/repo
# Type of contribution and how it can be featured as gallery content
# Keep only the type and content relevant to your contribution
# For a Shiny app, provide its URL:
type: shiny
content: https://user.shinyapps.io/my-app # e.g. my-app on shinyapps.io
# For a general online-published resource (e.g. a website / report):
type: webpage
content: https://user.github.io/my-analysis # URL of the webpage
# For more complex / heterogeneous contributions, you can create a GitHub
# Gist (https://gist.github.com/) with the relevant information and pointers:
type: gist
content: <script...> # place here what you get from the "Embed" button
